cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
	url(r'^$', views.Detalle.as_view(),name="cart_detail"),
	url(r'^add/(?P<product_id>\d+)/$', views.Agregar.as_view(), name="cart_add"),
	url(r'^remove/(?P<product_id>\d+)/$', views.Remove.as_view(), name="cart_remove")
	
]

shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.Lista.as_view(), name="tienda"),
	url(r'^(?P<product_id>\d+)/$', views.Detalle.as_view(), name="detalle"),
]

tiendita/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cart import urls as cartUrls
from shop import urls as shopUrls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(cartUrls, namespace="cart")),
    url(r'^', include(shopUrls, namespace="shop")),
]

cart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

shop/models.py
from __future__ import unicode_literals
from django.db import models

class Product(models.Model):
	nombre = models.CharField(max_length=140)
	description = models.CharField(max_length=140, null=True,blank=True)
	price = models.FloatField()
	def __str__(self):
		return self.nombre
	

cart/forms.py
from django import forms

CHOICES = ((i,str(i)) for i in range(1,21))

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=CHOICES, coerce=int)
	update = forms.BooleanField(required=False,initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CartAddProductForm
from django.views.generic import View
from .cart import Cart
from shop.models import Product


class Agregar(View):
	def post(self,request,product_id):
		cart = Cart(request)
		product = get_object_or_404(Product,id=product_id)
		form = CartAddProductForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
		return redirect('cart:cart_detail')

class Remove(View):
	def get(self,request,product_id):
		cart = Cart(request)
		product = get_object_or_404(Product,id=product_id)
		cart.remove(product)
		return redirect('cart:cart_detail')

class Detalle(View):
	def get(self,request):
		cart = Cart(request)
		return render(request,'cart/detalle.html',{'cart':cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Product
from cart.forms import CartAddProductForm


class Lista(View):
	def get(self, request):
		productos = Product.objects.all().order_by('nombre')
		template_name = 'shop/lista.html'
		context = {
			'productos':productos
		}
		return render(request,template_name,context)

class Detalle(View):
	def get(self, request, product_id):
		template_name = 'shop/detalle.html'
		producto = get_object_or_404(Product,id=product_id)
		form = CartAddProductForm()
		context = {
			'producto':producto,
			'form':form
		}
		return render(request,template_name,context)

cart/templates/cart/detalle.html
<html>
	<head>
		<title>Carrito</title>
		<meta charset="utf-8">
	</head>
	<body>
		<div align="center">
		<h1>Tu pinche carrito</h1>
			<table border="1px">
				<thead>
					<tr>
						<th>Imagen</th>
						<th>Producto</th>
						<th>Descripción</th>
						<th>Cantidad</th>
						<th>Quitar</th>
						<th>Precio Unitario</th>
						<th>SubTotal</th>
					</tr>
				</thead>
				<tbody align="center">
					{%for item in cart%}
						{%with product=item.product%}
						<tr>
							<td>
								<img src="">
							</td>
							<td>
								{{product.nombre}}
							</td>
							<td>
								{{product.description}}
							</td>
							<td>
								{{item.quantity}}
							</td>
							<td>
								<a href="{%url 'cart:cart_remove' product.id%}">Quitar</a>
							</td>
							<td>
								$ {{item.price}}
							</td>
							<td>
								$ {{item.total_price}}
							</td>
						</tr>
						{%endwith%}
					{%endfor%}
					<tr>
						<td>Total</td>
						<td colspan="5"></td>
						<td>$ {{cart.get_total_price}}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</body>
</html>

shop/templates/shop/detalle.html
<div align="center">
	<h2>{{producto.nombre}}</h2>
	<h2>{{producto.description}}</h2>
	<h3>Precio: $ {{producto.price}}</h3>
	<form action="{%url 'cart:cart_add' producto.id%}" method="post">
		{%csrf_token%}
		{{form.as_p}}
		<input type="submit" value="Agregar al Carrito">
	</form>
</div>

shop/templates/shop/lista.html
<div align="center">
<h1>Esta es la lista chirga de Productos</h1>
	<ul>
		{%for producto in productos%}
		<li><a href="{%url 'shop:detalle' producto.id%}">
			<p>{{producto.nombre}} <span>{{producto.description}}</span></p>
		</a></li>
		{%empty%}
		<h2>No hay productos pa mostrar</h2>
		{%endfor%}
	</ul>
</div>